/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.teradata.edwdecoded.sql.idtarget;

import javax.swing.JOptionPane;

/**
 *
 * @author glennm
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        Debug.debugEnabled = true;
        debugEnabledMenuItem.setSelected(Debug.debugEnabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileActionButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        selectedLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        sqlTextArea = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        fileGoMenuItem = new javax.swing.JMenuItem();
        fileUseSelectedMenuItem = new javax.swing.JCheckBoxMenuItem();
        fileObjectAsIsMenuItemButton = new javax.swing.JRadioButtonMenuItem();
        fileFullyQualifiedMenuItemButton = new javax.swing.JRadioButtonMenuItem();
        fileBaseObjectMenuItemButton = new javax.swing.JRadioButtonMenuItem();
        debugEnabledMenuItem = new javax.swing.JCheckBoxMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        aboutMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        fileExitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teradata Identify Target of Query");

        jPanel1.setLayout(new java.awt.BorderLayout());

        statusLabel.setText("Enter Query");
        statusLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(statusLabel, java.awt.BorderLayout.SOUTH);

        selectedLabel.setText("Processing: All Text");
        selectedLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(selectedLabel, java.awt.BorderLayout.NORTH);

        sqlTextArea.setColumns(20);
        sqlTextArea.setRows(5);
        sqlTextArea.setMargin(new java.awt.Insets(5, 5, 5, 5));
        sqlTextArea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sqlTextAreaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(sqlTextArea);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");

        fileGoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        fileGoMenuItem.setText("Go");
        fileGoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileGoMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fileGoMenuItem);

        fileUseSelectedMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        fileUseSelectedMenuItem.setText("Use selected Text");
        fileUseSelectedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileUseSelectedMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fileUseSelectedMenuItem);

        fileObjectAsIsMenuItemButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        fileActionButtonGroup.add(fileObjectAsIsMenuItemButton);
        fileObjectAsIsMenuItemButton.setSelected(true);
        fileObjectAsIsMenuItemButton.setText("Return target as is");
        fileMenu.add(fileObjectAsIsMenuItemButton);

        fileFullyQualifiedMenuItemButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        fileActionButtonGroup.add(fileFullyQualifiedMenuItemButton);
        fileFullyQualifiedMenuItemButton.setText("Add defaultDb if unqualified");
        fileMenu.add(fileFullyQualifiedMenuItemButton);

        fileBaseObjectMenuItemButton.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        fileActionButtonGroup.add(fileBaseObjectMenuItemButton);
        fileBaseObjectMenuItemButton.setText("Return base object");
        fileMenu.add(fileBaseObjectMenuItemButton);

        debugEnabledMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        debugEnabledMenuItem.setSelected(true);
        debugEnabledMenuItem.setText("Debug on");
        debugEnabledMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debugEnabledMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(debugEnabledMenuItem);
        fileMenu.add(jSeparator2);

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(aboutMenuItem);
        fileMenu.add(jSeparator1);

        fileExitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        fileExitMenuItem.setText("Exit");
        fileExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(fileExitMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitMenuItemActionPerformed
        System.exit(Main.APP_SUCCESS);
    }//GEN-LAST:event_fileExitMenuItemActionPerformed

    private void fileGoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileGoMenuItemActionPerformed
        String sqlText;
        if (fileUseSelectedMenuItem.isSelected()) {
            sqlText = sqlTextArea.getSelectedText();
        } else {
            sqlText = sqlTextArea.getText();
        }
        if (sqlText == null || sqlText.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Please enter a query into the query window.", "No Query", JOptionPane.INFORMATION_MESSAGE);
        }
        
        String method;
        String target;
        if (fileFullyQualifiedMenuItemButton.isSelected()) {
            method = "Fully qualify";
            target = Main.idTarget("defaultDb", sqlText, false);
        } else if (fileObjectAsIsMenuItemButton.isSelected()) {
            method = "As is";
            target = Main.idTargetTableUDF(sqlText);
        } else {
            method = "Base object";
            target = Main.idTargetTableBaseUDF(sqlText);
        }
            
        
        String msg;
        if (target != null) {
            msg = "Target of query: " + target + " (" + method + ")";
        } else {
            msg = "Cannot identify target of query." ;
        }
        
        statusLabel.setText(msg);
        Debug.println(msg);
        
    }//GEN-LAST:event_fileGoMenuItemActionPerformed

    private void sqlTextAreaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sqlTextAreaKeyTyped
        statusLabel.setText(" ");
    }//GEN-LAST:event_sqlTextAreaKeyTyped

    private void fileUseSelectedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileUseSelectedMenuItemActionPerformed
        
        if (fileUseSelectedMenuItem.isSelected()) {
            selectedLabel.setText("Processing: Selected Text");
        } else {
            selectedLabel.setText("Processing: All Text");
        }
    }//GEN-LAST:event_fileUseSelectedMenuItemActionPerformed

    private void debugEnabledMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debugEnabledMenuItemActionPerformed
        Debug.debugEnabled = debugEnabledMenuItem.isSelected();
        System.out.println("Debug mode: " + Debug.debugEnabled);
    }//GEN-LAST:event_debugEnabledMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        JOptionPane.showMessageDialog(this, "Id Target of SQL\nVersion: " + Main.version, "Version", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_aboutMenuItemActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JCheckBoxMenuItem debugEnabledMenuItem;
    private javax.swing.ButtonGroup fileActionButtonGroup;
    private javax.swing.JRadioButtonMenuItem fileBaseObjectMenuItemButton;
    private javax.swing.JMenuItem fileExitMenuItem;
    private javax.swing.JRadioButtonMenuItem fileFullyQualifiedMenuItemButton;
    private javax.swing.JMenuItem fileGoMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JRadioButtonMenuItem fileObjectAsIsMenuItemButton;
    private javax.swing.JCheckBoxMenuItem fileUseSelectedMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel selectedLabel;
    private javax.swing.JTextArea sqlTextArea;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
